name: aura
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aioice==0.10.1
      - aiortc==1.14.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - asttokens==3.0.1
      - av==16.0.1
      - blinker==1.9.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - clip==1.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cycler==0.12.1
      - dearpygui==2.1.1
      - decorator==5.2.1
      - dnspython==2.8.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastapi==0.122.0
      - filelock==3.20.0
      - flask==3.1.2
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - google-crc32c==1.7.1
      - h11==0.16.0
      - idna==3.11
      - ifaddr==0.2.0
      - ipython==8.37.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jsonpickle==4.1.1
      - kiwisolver==1.4.9
      - lap==0.5.12
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - packaging==25.0
      - parso==0.8.5
      - pillow==12.0.0
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - pure-eval==0.2.3
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyee==13.0.0
      - pygments==2.19.2
      - pylibsrtp==1.0.0
      - pyopenssl==25.3.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyvis==0.3.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - scipy==1.15.3
      - six==1.17.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.50.0
      - sympy==1.14.0
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - ultralytics==8.3.231
      - ultralytics-thop==2.0.18
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
prefix: C:\Users\mango\anaconda3\envs\aura
